#!/bin/bash

set -eu

apt-get update
apt-get install aliyun-cli yj

rm -rf bucc/state
touch bucc/vars.yml
source <(bucc/bin/bucc env)

(
mkdir -p uploads/bucc-compiled-releases
cd uploads/bucc-compiled-releases
bucc int | yj -y - | \
  jq -r '.releases | map(select(.name | test("cpi") | not)) | .[].url' | \
  xargs -L1 wget
)

cd uploads
aliyun oss cp . oss://bucc-compiled-releases-us-east-1 --recursive --force

aliyun oss ls oss://bucc-compiled-releases-us-east-1/bucc-compiled-releases/
